### ISSUE TITLE
Edit form loading ALL keywords and ALL authors

### ISSUE THREAD

**Issue by MobileMaggie** [Ibercivis/EU-CS_platform#461] opened 2020-11-17 11:09 UTC
see: https://eu-citizen.science/editTrainingResource/137

**Comment by frasanz** [comment] 2020-11-23 07:59
@vvalvesga , this is an important one

**Comment by frasanz** [comment] 2020-11-23 09:20
Hi

We cant recreate the bug, can you explain the steps to get this bug?

**Comment by MobileMaggie** [comment] 2020-11-23 09:37
I was going into a form to try and edit it to add a header photo, and ALL
of the keywords loaded and ALL of the authors loaded. When I saved, they
all saved. I couldn't delete them.

**Comment by frasanz** [comment] 2020-11-23 09:44
Can you re-do with me and Victor in skype?

**Comment by MobileMaggie** [comment] 2020-11-23 09:47
Just checked, and it's not happening any more....strange. a one-off bug.

**Comment by MobileMaggie** [comment] 2020-11-23 16:21
I just had it happen again - moved the Biodiversa training over to resource, opened it to add a new header for it, and the form loaded ALL of the keywords and authors again
<img width="1440" alt="Screenshot 2020-11-23 at 16 48 54" src="https://user-images.githubusercontent.com/1629708/99987016-3add2e80-2db0-11eb-80ae-8061cb950a8f.png">
<img width="1440" alt="Screenshot 2020-11-23 at 16 48 49" src="https://user-images.githubusercontent.com/1629708/99987026-403a7900-2db0-11eb-9c3a-79cbceea9d1a.png">
<img width="1440" alt="Screenshot 2020-11-23 at 16 48 59" src="https://user-images.githubusercontent.com/1629708/99987042-429cd300-2db0-11eb-9c21-a8ba36e17d7b.png">

**Comment by frasanz** [comment] 2020-11-23 20:27
Great thanks!

Let's go over it Victor

**Comment by vvalvesga** [comment] 2020-11-24 11:54
I don't see any errors. What will have happened is that all those authors and keywords have been entered.
I think you have gone to edit but all those authors and keywords were already saved.
I have left it with an author and a keyword and passed from training to resource and viceversa and it kept the changes.

**Comment by frasanz** [comment] 2020-11-24 12:00
I don't think so because Margaret didn't do that. @Margaret Gold
<mg@margaretgold.co.uk> , which browser did you use when the bug appeared?

Fran

**Comment by vvalvesga** [comment] 2020-11-24 12:11
But for now, only had occured in resource 137. Try again Margaret, now they shouldn't all leave, only two authors and keywords I entered

**Comment by frasanz** [comment] 2020-11-24 12:18
Resoource 72 also has lots of authors
https://eu-citizen.science/editResource/72

I have erased keywords/authors in at least two more resources (I don't
remember the ids)

Let's go to other issues but we need to come back to this once @Margaret
Gold <mg@margaretgold.co.uk> can provide us further information

**Comment by vvalvesga** [comment] 2020-11-25 12:16
@frasanz update production and check this functionality deleting and saving again.

**Comment by frasanz** [comment] 2020-11-25 12:24
The server is now updated with the last version. @Margaret Gold
<mg@margaretgold.co.uk> , if you have time, please try to redo the bug
using a fake project/resource

**Comment by frasanz** [comment] 2020-11-26 08:51
It seems that the bug is here again (after server update)

https://eu-citizen.science/resource/140

**Comment by vvalvesga** [comment] 2021-01-15 08:05
I close it because we have not been able to reproduce the error and it may have been fixed since it has not been reported again.

**Closed by vvalvesga** 2021-01-15 08:05 UTC
Labels: Critical, bug
